### ISSUE TITLE
Files on deduplicated NTFS volumes are ignored by scanner

### ISSUE THREAD

**Issue by NTmatter** [syncthing/syncthing#1845]
When adding a folder on a volume with NTFS Deduplication enabled, deduped files are incorrectly skipped by the scanner. Files that are still pending deduplication are processed as expected. Folders are also processed as normal.

A bit of digging indicates that os.Lstat on a deduped file has a FileMode containing ModeSymLink. Looking at the Read function in [symlink_windows.go](https://github.com/syncthing/syncthing/blob/master/internal/symlinks/symlink_windows.go#L104), the type of reparse point is available in reparseData.reparseTag, which should allow for correctly handling the condition. 

A quick reference to the tag values is available in [smbfsctl.h](https://github.com/torvalds/linux/blob/master/fs/cifs/smbfsctl.h#L100). Of interest are:
- IO_REPARSE_TAG_DEDUP = 0x80000013
- IO_REPARSE_TAG_SYMLINK = 0xA000000C
- IO_REPARSE_TAG_MOUNT_POINT = 0xA0000003 (may be related to #1830)
- More info about [Reparse Points](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365511%28v=vs.85%29.aspx) and supported operations

For reference, it is possible to query a reparse point's tag and data with <code>fsutil reparsepoint query PATH_TO_FILE</code>. This even works across SMB shares with UNC paths.

**Comment by calmh** [comment]
(Needs someone who knows and loves Windows)

**Comment by NTmatter** [comment]
(same here :smiley: - but there's some fun to be found in the learning and the doing!)

Some tests with stfileinfo show that <code>Scanner.Blocks</code> happily consumes a handle to a deduped file, producing the same results as a normal version of the same file. This indicates that the existing functionality already handles reparse points fairly well.

I'll see if I can hack together a proof of concept that behaves acceptably for a read-only master.

**Comment by NTmatter** [comment]
After some additional digging, it looks like any call to os.Stat() will fail when it hits a deduplicated file. Properly handling this will require changing every os.Stat() call to os.Lstat() with a sanity check and appropriate handling.

By the looks of it, os.Stat() is [blindly checking](https://github.com/golang/go/blob/439b32936367c3efd0dadab48dd51202e1a510f1/src/os/stat_windows.go#L57) for the Symlink bit, then calling Readlink which [bails out](https://github.com/golang/go/blob/439b32936367c3efd0dadab48dd51202e1a510f1/src/syscall/syscall_windows.go#L1005-L1007) because it doesn't know about the Deduplication tag.

**Comment by NTmatter** [comment]
Bug filed upstream as golang/go#10935.

**Comment by calmh** [comment]
:+1:

**Comment by calmh** [comment]
(This is still pending upstream)

**Comment by calmh** [comment]
This is now solved upstream so it would be interesting to know if it now works for us or not.

**Comment by niphlod** [comment]
+1 on that

**Comment by zechnkaas** [comment]
Hi,

do i have to enable something special? Tried it in some Testing environment. Set up complete new Syncthing environment (V14.41) Deduped Files are still not synced. Status of Folder also still shows wrong size.

ty
![image](https://user-images.githubusercontent.com/7140356/33822736-eae3f462-de58-11e7-87d9-2501a28c7032.png)
![image](https://user-images.githubusercontent.com/7140356/33822753-00486c48-de59-11e7-83df-df02e4fcb850.png)

**Comment by AudriusButkevicius** [comment]
I don't think it work, as they still show up as symlinks.

**Comment by niphlod** [comment]
I'm absolutely not a go dev but another go project solved it. Is it possible to follow the same route?
 https://github.com/minio/minio/pull/4203

**Comment by calmh** [comment]
We already have that fix by way of it being included in Go 1.9 which we’ve used for a while. If this still doesn’t work, it’s something else.

**Comment by niphlod** [comment]
thanks for the pointer, they indeed do still not work as of 0.14.42. 
This though begs a question....If that fix has been included upstream why does minio work flawlessy while syncthing doesn't ?

**Comment by AudriusButkevicius** [comment]
What exactly works in minio? Perhaps minio doesn't care about traversing symlinks.

**Comment by niphlod** [comment]
minio can serve deduplicated files fine, so it found a way to read its contents as if there were "normal" files rather than symlinks.

**Comment by AudriusButkevicius** [comment]
Well we can read symlinks but we choose not to due to security implications.

**Comment by calmh** [comment]
Again this is the question. Do Windows present these files as symlinks? If so it is by design that we do not process them. If Windows does not, it's a bug that we don't process them.

**Comment by AudriusButkevicius** [comment]
Well I don't have windows with a fancy filesystem to verify this.

**Comment by niphlod** [comment]
how can I help on clarify this "doubt" ?
Windows does not present these files as "usual" symlinks (created with `mklink target path_to\file.ext`). Usual symlinks have a "nice" shortcut icon (bar.bak in the photo).
Deduped files look....normal files, if you inspect properties, you see differences in "size on disk" and "size", as foo.bak

![image](https://user-images.githubusercontent.com/122119/34436373-aaf3b180-ec95-11e7-9e98-92374263592d.png)
 

 
If that's a choice, oookay then. 
This issue should be closed as wontfix without leading users/coders into thinking deduped files are not supported because of a bug in a fantastic piece of software but because of a choice. 
I get the security implications (those can be "tamed" allowing just file symlinks and not directory symlinks), but given the spread deduped files are getting (and more than a hundred hits on the relevant post on discourse), I'd then create an issue for having a per-folder setting to follow symlinks to make folders in deduped drives work on windows as "expected".

**Comment by AudriusButkevicius** [comment]
Well that's how the explorer displays them, but it's most likely miles away from how go might see them. You need to write a small go program doing os.Stat and os Lstat on a deduped file and provide the outcome of that.

**Comment by niphlod** [comment]
ok, I'll try and post back findings. thanks for the help and sorry for the bashing on this matter ^_^

**Comment by calmh** [comment]
Run this one one of the files: https://kastelo.net/t/stfileinfo.exe

**Comment by niphlod** [comment]
```
File:
  e:\minio\simo\foo.bak

Lstat:
  Size: 392302080 bytes
  Mode: 01000000666
  Time: 2017-12-29 11:49:46.1769994 +0100 CET
        1514544586.176999400

Stat:
  Size: 392302080 bytes
  Mode: 0666
  Time: 2017-12-29 11:49:46.1769994 +0100 CET
        1514544586.176999400

Blocks:
  Block{0/392302080/437468685/4b12715415e783339d60e8048247328b30ea61910cc45a6dfbd111a10d5de95e}
```
vs
```
File:
  e:\minio\simo\bar.bak

Lstat:
  Size: 0 bytes
  Mode: 01000000666
  Time: 2017-12-29 12:40:57.9818913 +0100 CET
        1514547657.981891300

Stat:
  Size: 6528454 bytes
  Mode: 0666
  Time: 2016-11-19 00:37:17.0969683 +0100 CET
        1479512237.096968300

Blocks:
  Block{0/6528454/3688470918/6bb6d11da01f2a2c44c90ff4e0f4b77849169916df3ae3cbcec2b0057bf408f1}

```

**Comment by calmh** [comment]
Both of those have the symlink bit set in the Stat() response, that's the really high one in "mode". So as far as Go 1.10 (which compiled that binary) can tell, they are both symlinks. They are also both pretty odd with the sizes.

**Comment by niphlod** [comment]
both odd sizes ? 
bar.bak is the "usual symlink" and reports different sizes, but foo.bak, which is the deduped file does not ....
However I see the point. Basically if the "mode" is the same there's no way for syncthing to know.

**Comment by calmh** [comment]
Sorry, just "odd" from a unix perspective where the symlink contains the target name so the size is the length of that, making both zero and hundreds of megs impossible. And I guess if we wanted to do something here we could trigger on "IsWindows && isSymlink && Size > 0" and then consider that a regular file. If someone can guarantee under oath and with penalty of ... having to apologize, that that combination of factors can only happen for files that are real files but deduplicated.

**Comment by niphlod** [comment]
AFAIK if we're just speaking about files in windows there are 3 ways to "simulate" a link.
1) shortcut (right click, create shortcut). This is just a "regular" file with an lnk extension, which syncthing already manages. It does not show any size changes if the "linked real file" changes, as it's a proper file (docs for the curious [here](https://msdn.microsoft.com/en-us/library/dd871305.aspx)). I created a baz.bak, and this is the result from stfileinfo
```
File:
  e:\minio\simo\baz.bak.lnk

Lstat:
  Size: 899 bytes
  Mode: 0666
  Time: 2017-12-29 14:41:50.770511 +0100 CET
        1514554910.770511000

Blocks:
  Block{0/899/161789426/6b705b49dd740b8397c4268f12c86e23c24295f8d0f37d2122f7b252b7ead1ad}
```
2) symbolic link, as `bar.bak` before, created with `mklink bar.bak path_to\file.ext`. This can spawn drives (i.e. `path_to\file.ext` can be in a different drive than `bar.bak`). Reported in explorer as ".symlink" type, with a shortcut icon, 0 Bytes of Size, 0 Bytes on Disk.
3) "hard link", created with `mklink /H qux.bak path_to\file.ext`. This cannot spawn drives (i.e. `path_to\file.ext` MUST be in the same drive than `qux.bak`). Reported in explorer as the original file, no shortcut icon, 0 Bytes of Size, n Bytes on Disk. This is the most "resemblant" to a deduped file via explorer "properties", and here's the result from stfileinfo
```
File:
  e:\minio\simo\qux.bak

Lstat:
  Size: 6528454 bytes
  Mode: 01000000666
  Time: 2016-11-19 00:37:17.0969683 +0100 CET
        1479512237.096968300

Stat:
  Size: 6528454 bytes
  Mode: 0666
  Time: 2016-11-19 00:37:17.0969683 +0100 CET
        1479512237.096968300

Blocks:
  Block{0/6528454/3688470918/6bb6d11da01f2a2c44c90ff4e0f4b77849169916df3ae3cbcec2b0057bf408f1}
```

So...
1) is already okay, or at least is handled like a regular lnk
2) is a "soft" symlink
3) is an "hard" symlink
to support deduped files, which have the same properties as 3), syntching will effectively need to process  "hard" symlinks too: either it handles them or it won't.

If syncthing wanna support deduped files, it means that:
- if the source holds qux.bak the dest will have a qux.bak file with the same contents on the "underlying linked file", with size (both "real" and "on disk") that matches the  "underlying linked file"
- if foo.bak is in the source, the same deal will apply for it on the dest, that will have a foo.bak file with the same contents on the "underlying undeduped file", with size (both "real" and "on disk") that matches the  "underlying undeduped file". If the dedupe feature is enabled on dest, foo.bak will be matching the same stats seen on the source after the first pass, but that's going on outside syncthing.

**Comment by calmh** [comment]
So it seems these "hard" symlinks inherit the properties of their target, as the symlink doesn't have its own mtime or size in the output above. (A "real" symlink does have its own owner, permissions, mtime, etc.)

One curious question though - what does look like for two files that are in fact identical and have been deduplication to the same thing? Logically they should be "links" of some kind to the same data, yet the link can't be a link as such because modifying one should not modify the other, and the mtime/modes/etc should be individual.

**Comment by niphlod** [comment]
yup, hardlinks show time,owner and perms the same of the target. size is the only "tell". If you change owner on the "link", it's applied to the "linked". If you change perms on the "linked", "link" also reflect that change. 

deduped files, even identical ones, have each their own "metadata" (time, owner, perms, etc), so even if they are "summed" to the same set of "basic blocks" because they're identical, a change in one doesn't trigger a change in the other. Internally it basically translates to a number of files stored within "System Volume Information" and a service (plus a layered driver) that composes the content accordingly.

**Comment by calmh** [comment]
Right, then. Can someone dig up something from MSDN or similar authoritative source that we can trust that symlink(reparse point, whatever)+nonzero-size is in fact a real file despite the symlink flag?

**Comment by calmh** [comment]
Another option would be to say that symlinks on Windows are currently admin- and develop-only, and we can follow them without security issues. (Although clearly not create them.)

**Comment by AudriusButkevicius** [comment]
Sorry, but if the link has non-zero size, is that not enough to say it's not a symlink but in fact a reparse point and we should follow that?

**Comment by niphlod** [comment]
for all matters and purposes, as dedup is an async operation, the only attribute changing when the file gets deduped is "size on disk". 
For hardlinks, size on disk is always 0.
For deduped files, as soon as the async process finishes doing "its things", size on disk is reported as 0, no matter what "dedupeability" it has.

**Comment by calmh** [comment]
Yes that could be enough. Unless, like, symlinks to deduplicated directories or something else bizarre *also* get the size reported. That's the point I want confirmed.

**Comment by niphlod** [comment]
we're just talking file links here, not directories. it just boils down to handle BOTH hardlinks and deduped files in the source as "the underlying files" or not.

**Comment by calmh** [comment]
Are we sure every type of symlink to a directory shows the directory bit in the Lstat return? (This is not the case on Unix, but I think/hope it is on Windows?)

**Comment by niphlod** [comment]
aren't we going a bit off-track ? 
This issue is "support files on deduplicated volumes". We saw how deduped files are detected by go on windows, but there's no way to discern them from "hardlinks" (both are flagged as symlinks with matching size in lstat and stat)
 
If syncthing doesn't support in any other platform directory links because of security issues (which is outside of this issue's scope), why should it on windows ?

**Comment by niphlod** [comment]
for the sake of completeness, I ran stfileinfo on two dirs, one softlink (dir1) and one junction point (dir2).
```
File:
  e:\minio\simo\dir1

Lstat:
  Size: 0 bytes
  Mode: 01000000666
  Time: 2017-12-29 16:14:22.3486578 +0100 CET
        1514560462.348657800

Stat:
  Size: 4096 bytes
  Mode: 020000000777
  Time: 2017-12-29 14:43:13.0586186 +0100 CET
        1514554993.058618600
```
```
File:
  e:\minio\simo\dir2

Lstat:
  Size: 0 bytes
  Mode: 01000000666
  Time: 2017-12-29 16:17:00.9990184 +0100 CET
        1514560620.999018400

Stat:
  Size: 0 bytes
  Mode: 020000000777
  Time: 2017-12-29 15:50:27.7177478 +0100 CET
        1514559027.717747800
```
