### ISSUE TITLE
Provide docker-compose.yml example in README

### ISSUE THREAD

**Issue by pirate** [syncthing/syncthing#5221]
Many people use docker-compose to define interactions between their docker containers, but when googling "Syncthing docker-compose" the only results are very out of date, or use non-official Docker images.

Perhaps we could add an example `docker-compose.yml` to the project root:

```
version: '3'

services:
  syncthing:
    image: syncthing/syncthing
    restart: always
    ports:
      - "8384:8384"
      - "22000:22000"
      - "21027:21027/udp"

    volumes:
      - "./config:/var/syncthing/.config/syncthing"
      - "./data:/var/syncthing"
```

PR: https://github.com/syncthing/syncthing/pull/7355
