### ISSUE TITLE
"Sysctl permission denied" with the docker compose snippet in docker-README

### ISSUE THREAD

**Issue by ManuelSchneid3r** [syncthing/syncthing#7542]
The line `--sysctl net.core.rmem_max=2097152` in the docker snippet as well as its compose counterpart make the image to fail running. I found this note in the docker docs: [Docker does not support changing sysctls inside a container that also modify the host system](https://docs.docker.com/compose/compose-file/compose-file-v3/#sysctls). Also see the section [CURRENTLY SUPPORTED SYSCTLS](https://docs.docker.com/engine/reference/commandline/run/#configure-namespaced-kernel-parameters-sysctls-at-runtime).

Is this a bug or am I doin it wrong?

**Comment by imsodin** [comment]
From your link:
> You can only use sysctls that are namespaced in the kernel. Docker does not support changing sysctls inside a container that also modify the host system.

> Network Namespace:
> 
>     Sysctls beginning with net.*
>     If you use the --network=host option using these sysctls are not allowed.

So `--sysctl net.core.rmem_max=2097152` is fine as long as you don't use `--network=host`. If you do, you can/need to adjust it it directly on the host.

**Comment by canidorichard** [comment]
The --sysctl net.core.rmem_max=2097152 option cuases failure even without --network=host.

It appears that /proc/sys/net/core/rmem_max is not available inside the container.  The following error messages is produced when attempting to start the container with this parameter:

>docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: write sysctl key net.core.rmem_max: open /proc/sys/net/core/rmem_max: no such file or directory: unknown.`

**Comment by Taubin** [comment]
I'm receiving the same error on attempting to use the docker-compose file. 

```
ERROR: for c396deb4b344_syncthing  Cannot start service syncthing: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: write sysctl key net.core.rmem_max: open /proc/sys/net/core/rmem_max: no such file or directory: unknown

ERROR: for syncthing  Cannot start service syncthing: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: write sysctl key net.core.rmem_max: open /proc/sys/net/core/rmem_max: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```

My full compose (copied and pasted from the version on github)
```

---
version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncthing.taubin.cc
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /sync:/var/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    sysctls:
      - net.core.rmem_max=2097152
    restart: unless-stopped
```
