### ISSUE TITLE
error: unknown flag --log-max-files

### ISSUE THREAD

**Issue by fede843** [syncthing/syncthing#8095]
Hello, I am using docker syncthing version 1.18.5.

I am trying to polish the loging side, and I found a possible issue when trying to use the "--log-max-files" flag.

This is the part from docker compose file that deal with this:

```
version: '3.9'
services:
  syncthing:
    image: syncthing/syncthing:1.18.5
    container_name: syncthing
    hostname: syncthing
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Sydney
      - STGUIADDRESS=
    command: "--logflags=5 --log-max-size=1073741824 --logfile=/var/log/syncthing.log --log-max-files=2"
```
all added flags work just fine as expected, but if I left "--log-max-files" it throws next error when try to run it:

`syncthing: error: unknown flag --log-max-files
`

Also I checked removing it, and has an implicit limit of 3 extra files, which is fine, but I would like to know if that is adjustable.

Thanks!
