### ISSUE TITLE
Docker image keeps exiting with exit 0

### ISSUE THREAD

**Issue by grantland** [syncthing/syncthing#8292]
I'm running syncthing on a pi4 running raspbian with docker-compose and I'm noticing that my service keeps going down. Every time this happens, `docker-compose ps` shows that syncthing exited with code 0, which is confusing since that should be the successful error code and AFAIK syncthing shouldn't exit:

```
$ docker-compose ps
  Name                 Command               State                                 Ports                              
----------------------------------------------------------------------------------------------------------------------
syncthing   /bin/entrypoint.sh /bin/sy ...   Exit 0   21027/udp, 0.0.0.0:22000->22000/tcp, 0.0.0.0:22000->22000/udp,  
                                                      0.0.0.0:8384->8384/tcp 
```

I've checked `docker logs syncthing` and I seem to get `Syncthing exited: signal: killed` without much more information and other times nothing as the last message:

```
[PN2BU] 21:52:19 INFO: Device ****** client is "syncthing v1.19.2" named "******" at 172.21.0.2:50442-170.178.211.213:22067/relay-server/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
[monitor] 00:04:53 INFO: Syncthing exited: signal: killed
[start] 00:04:54 INFO: syncthing v1.19.2 "Fermium Flea" (go1.17.7 linux-arm) docker@build.syncthing.net 2022-03-21 03:47:47 UTC [noupgrade]
...
[PN2BU] 17:39:10 INFO: Joined relay relay://104.193.226.100:22067
[PN2BU] 17:48:15 INFO: Completed initial scan of receiveencrypted folder "Default Folder" (szn99-uxvgv)
[start] 11:33:07 INFO: syncthing v1.19.2 "Fermium Flea" (go1.17.7 linux-arm) docker@build.syncthing.net 2022-03-21 03:47:47 UTC [noupgrade]
```

Also my `docker-compose.yml`:

```
version: '3'
services:

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
    volumes:
      - /home/grantland/syncthing/config:/var/syncthing/config
      - /media/storage/syncthing:/data
      - /media/storage:/media/storage
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    restart: unless-stopped
```

Are there logs somewhere else that might show me why syncthing keeps exiting? FWIW this is an encrypted node which is in beta.

Thanks!
