### ISSUE TITLE
cmd/stdiscosrv: no certificates: empty certificate header

### ISSUE THREAD

**Issue by imkos** [syncthing/syncthing#8306]
env:
k8s

ingress:
```
spec:
  rules:
  - host: discovery.*****.com
    http:
      paths:
      - backend:
          service:
            name: stdiscosrv
            port:
              number: 8443
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - discovery.***.com
    secretName: ****

```

start cmd:
/bin/stdiscosrv -http

Reference link: https://docs.syncthing.net/users/stdiscosrv.html#reverse-proxy-setup
