### ISSUE TITLE
Listen (BEP/tcp): listen tcp 192.168.1.2:22000: bind: cannot assign requested address

### ISSUE THREAD

**Issue by ispmarin** [syncthing/syncthing#8514]
### Include required information

Please be sure to include at least:
- Syncthing version 1.20.4 on Debian bullseye
- Running docker container with
```
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${SYNCTHING_STORAGE_PATH}:/var/syncthing
      - /data/images:/data/images
    networks:
      - homelab
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
```
- both firefox and safari (latest versions)

The problem: I disabled global discovery, keeping only local discovery, and changed the listen address to `tcp://<ip of machine where syncthing is running>:22000`. This works on MacOS, but on the Linux machine, discovery only works if I change the listen address to `tcp://0.0.0.0:22000`. There is nothing in my system running on port 22000, and this error is appearing inside the docker container. I don't want to enable global discovery. Any idea on why the syncthing service inside the docker container is throwing these errors? 

```
[VBRO4] 2022/08/25 17:42:20 INFO: Listen (BEP/tcp): listen tcp 192.168.1.2:22000: bind: cannot assign requested address
[VBRO4] 2022/08/25 17:42:20 INFO: listenerSupervisor@tcp://sync.tunguska.cc:22000: service tcp://sync.tunguska.cc:22000 failed: listen tcp 192.168.1.2:22000: bind: cannot assign requested address
[VBRO4] 2022/08/25 17:42:20 INFO: Listen (BEP/tcp): listen tcp 192.168.1.2:22000: bind: cannot assign requested address
[VBRO4] 2022/08/25 17:42:20 INFO: listenerSupervisor@tcp://sync.tunguska.cc:22000: service tcp://sync.tunguska.cc:22000 failed: listen tcp 192.168.1.2:22000: bind: cannot assign requested address
[VBRO4] 2022/08/25 17:42:20 INFO: Listen (BEP/tcp): listen tcp 192.168.1.2:22000: bind: cannot assign requested address
[VBRO4] 2022/08/25 17:42:20 INFO: listenerSupervisor@tcp://sync.tunguska.cc:22000: service tcp://sync.tunguska.cc:22000 failed: listen tcp 192.168.1.2:22000: bind: cannot assign requested address
[VBRO4] 2022/08/25 17:42:41 INFO: Listen (BEP/tcp): listen tcp 192.168.1.2:22000: bind: cannot assign requested address
[VBRO4] 2022/08/25 17:42:41 INFO: Listen (BEP/tcp): listen tcp 192.168.1.2:22000: bind: cannot assign requested address
[VBRO4] 2022/08/25 17:42:41 INFO: Listen (BEP/tcp): listen tcp 192.168.1.2:22000: bind: cannot assign requested address
[VBRO4] 2022/08/25 17:44:06 INFO: Listen (BEP/tcp): listen tcp 192.168.1.2:22000: bind: cannot assign requested address
[VBRO4] 2022/08/25 17:44:06 INFO: Listen (BEP/tcp): listen tcp 192.168.1.2:22000: bind: cannot assign requested address
[VBRO4] 2022/08/25 17:44:06 INFO: Listen (BEP/tcp): listen tcp 192.168.1.2:22000: bind: cannot assign requested address
```
