### ISSUE TITLE
Docker RC - Fails to start at entrypoint 'PCAP: parameter not set' 

### ISSUE THREAD

**Issue by DavidFair** [syncthing/syncthing#8567]
On startup Docker Swarm now gives the following error with the latest release candidate:
`/bin/entrypoint.sh: line 7: PCAP: parameter not set`

This looks like it comes from #8552 as the `latest` (non-rc) tag works correctly (albeit unhappy about the config downgrade as expected)

### Include required information

Version: Latest `syncthing/syncthing:rc`
Attached below is my compose which I'm deploying using Swarm:
```
version: "3"

services:
  syncthing:
    image: "syncthing/syncthing:rc"
    ports:
      - 8384:8384
      - 22000:22000
      - 22000:22000/udp
      - 21027:21027/udp
    environment:
      - PUID=1200
      - PGID=1200
      - DOMAIN=<domain>
      - STGUIADDRESS=0.0.0.0:8384
    volumes:
      - /pool/docker_volumes/syncthing/config:/var/syncthing/config
      - /pool/syncthing/Data:/data
    networks:
      - traefik
    deploy:
      placement:
        constraints:
          - node.hostname==zfs-server
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.syncthing.rule=Host(`<domain>`)"
        - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
        - "traefik.http.routers.syncthing.middlewares=authelia@file"

networks:
  traefik:
    external: true
```
