### ISSUE TITLE
Syncthing in Docker doesn't redirect to HTTPS when "Use HTTPS for GUI" is checked

### ISSUE THREAD

**Issue by huyi51462** [syncthing/syncthing#9385]
Syncthing version : Docker 1.26.* 1.27.* 
os                          : docker
browser version    : Chrome  120.0.6099.225
what happened    :  when enable "Use HTTPS for GUI", syncthing gui can not redirect to https
expected               :  when enable "Use HTTPS for GUI" , syncthing gui can redirect http to https 

here is compose file
```
version: "3"
syncthing:
    image: syncthing/syncthing:1.25
    container_name: syncthing
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /syncthing/syncthing:/var/syncthing
```
