### ISSUE TITLE
Make it possible to prefer UID/GID over usernames when syncing permissions

### ISSUE THREAD

**Issue by spkane** [syncthing/syncthing#9559]
### Feature description

Make it possible to have Syncthing prefer using the UID/GID for permissions syncing BEFORE the username, instead of after it, which appears to be the default behaviour today.Make it possible to have Syncthing prefer using the UID/GID for permissions syncing BEFORE the username instead of after it, which appears to be the default behavior today.

### Problem or use case

Discussion: https://forum.syncthing.net/t/syncownership-macos/22155/7

If you are syncing between 2 systems where Syncthing is being run by the same UID (e.g. 500), but a different username:

e.g.

```yaml
system-one:
  sean: "UID 500"

system-two:
  alice: "UID 500"
```

But one of the systems has another UID with a username matching the other system:

e.g.

```yaml
system-one:
  sean: "UID 500"

system-two:
  alice: "UID 500"
  sean: "UID 501"
```

In this case a file owned by `sean - UID 500` being sent from `system-one`  to `system-two` , will fail to have it permissions set, since Syncthing will use the username and that will result in `system-two`'s alice user trying to change the file to be owned by `sean - UID501`.

### Alternatives or workarounds

Not aware of any, besides avoiding this situation when possible.
